
[workspace]
resolver = "2"
members = [
    "proto",
    "lib",
    "sim",
    "cli",
]

[patch.crates-io]
ledger-proto = { path = "proto" }
ledger-lib = { path = "lib" }
ledger-sim = { path = "sim" }
